changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - pre-commit-ci
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Security
      labels:
        - security
    - title: Internal Changes
      labels:
        - refactor
        - test
      exclude:
        labels:
          - build
          - package
          - documentation
    - title: Documentation
      labels:
        - documentation
    - title: Build and Packaging
      labels:
        - build
        - package
    - title: Uncategorized Changes
      labels:
        - "*"
