import random

import os
import pathlib
import subprocess

# this can run in a fairly arbitrary python

# There should be several versions available.
# Actually the number is unbounded because tests might want to be able
# to start up arbitrary other components of arbitrary version... but
# for now, a client-ish, and exchange-ish, and an agent-ish.

# these can be chosen in various combos: earliest that matches the version constraint,
# most recent, "pr current", random from main branch, random release that matches (a subset of random-from-main)

# these envs can also contain other version constrains eventaully, not only academy version.
# (python version, redis version, ...). python version is probably especially useful for being able to
# deal with peoples marginal ideas on cross-python compatibility.

# The notion of a current/here version is special though because that's where this driver script and the tests
# live (probably) - and might exist only as a current filesystem artefact, unlike the other globally named
# versions.

# It makes sense to run the current version against a *later* version (as part of testing that later version)
# which itself is a bit nuanced -- I want to know that what i am writing now is not broken by future changes.

# It's also possible I want to test API consistency, not just wire protocol consistency? what does that look
# like? Test cases from version x, but run against version y (so that if someone edits the test cases to make
# version y work, we discover than when running the version x tests)?  Or is that covered by "do not edit these
# tests without an API bump or untested-justification of how this isn't breaking things?"
# Testing this API compatibility is probably interesting/useful though.
# And at least good for modelling what version meanings are in that space, separate from wire protocols.
# There will be testing of that a bit though -- we'll be testing that the Python test code from HERE will run
# in an environment where we've got V1, or V2, or V3 installed.

# Config file format is also a thing: if i generate a config file now, does it work across older and newer
# versions? - for example, the config file for the http exchange. if I generate it "now" (aka from this current
# version of the test suite), will it be accepted by future and past implementations of the http exchange?

# are all these versioned by the same version (the pypi package version) or is there more interesting stuff
# going on that users (and academy code) needs to understand?

V1={"academy": "origin/main"}
V2=V1
V3=V1

# basic test model is:
# a submitter/client
# an exchange process
# an agent process

# we are going to test that we can do a ping to the agent.

# In this level, we should not be expecting any academy to be installed
# because there's no meaningful version to be active - there are 3. Anything
# academy-like has to happen in the relevant environments.

def create_env(descr: dict) -> pathlib.Path:
    path = pathlib.Path(".") / ("crossver-env-" + str(random.randint(0,999999999)))

    print(f"creating env for {descr} at {path}")

    dir = path.mkdir()

    p1 = os.getcwd()

    os.chdir(path)

    os.system(f"virtualenv ./venv; pwd; ls; . ./venv/bin/activate; which python; pip install {p1}")

    os.chdir(p1)

    return path
    

v1_env = create_env(V1)
v2_env = create_env(V2)
v3_env = create_env(V3)

# now i need something like an integration test, but clearly split into three environments...
# and to separately and concurrently run the three components.
# (rather than the in-python test fixture starting up an agent inside the same Python function
# as the client)


# first startup an exchange
# type of exchange could be parametrizable but it needs to be at least cross process accessible - 
# so redis and http?
# a redis exchange has no active process and no active code - it's a shared redis instance. so it
# wont' need its own environment to be installed.

# V1 is the http exchange environment

# the config file is generated by HERE, not by the V1 environment,
# because I expect a config file for the http exchange to be compatible across versions.
# This config was originally sourced from tests/unit/exchange/cloud/app_test.py 


exchange_config = """
host = "localhost"
port = 1234
"""

with open(v1_env / "exchange_config.json", "w") as f:
    f.write(exchange_config)


# now run some kind of process group that is async wrt rest of program and can be shut down
# entirely at the end (not just the process but all children)


# p1 = subprocess.Popen(["cd", v1_env, ";", "ls"], shell=True, process_group=0)
p1 = subprocess.Popen("echo hello", shell=True, process_group=0)

import time
time.sleep(10)

print("terminating p1")
p1.terminate()

print("waiting on p1")
p1.wait()

