name: Feature request
description: Request a new feature or enhancement.
labels: ["enhancement"]
body:
  - type: textarea
    id: request
    attributes:
      label: Describe the Request
      description: >
        Please describe the new functionality, why it is needed, and how it would be used. Include any relevant context.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Sample Code
      description: >
        If relevant, please provide sample code such as the proposed
        interface, usage, or results. **Note:** this will be rendered as
        Python code automatically.
      render: python
    validations:
      required: false
